---
settings:
  name: E-Series Family
  search: e-series,e-series-santricity,e-series-cli
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation sur la gamme de produits E-Series
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: Tous les documents
    tags: tag_storage_management,tag_data_storage,tag_cli,tag_get_started,tag_SANtricity,
      tag_solution
    class: active
  - title: Commencez
    tags: tag_get_started
  - title: Stockage des données
    tags: tag_data_storage
  - title: Gestion du stockage
    tags: tag_storage_management, tag_SANtricity
  - title: NetApp
    tags: tag_solution
  tiles:
  - title: En savoir plus sur la gamme E-Series
    icon: "./media/groups_line-1.png"
    url: intro-family.html
    summary: Découvrez la gamme E-Series de systèmes de stockage.
    tags: all, tag_get_started
  - title: Systèmes E-Series
    icon: "./media/system_line.png"
    url: https://docs.netapp.com/us-en/e-series/index.html
    summary: Gérez vos workloads applicatifs grâce à un stockage bloc rapide et à
      une fiabilité exceptionnelle.
    tags: all, tag_data_storage
  - title: Logiciel SANtricity
    icon: "./media/config_line.png"
    url: https://docs.netapp.com/us-en/e-series-santricity/index.html
    summary: Le logiciel SANtricity permet de provisionner et de gérer vos systèmes
      de stockage E-Series à partir d'une interface web.
    tags: all, tag_storage_management, tag_SANtricity
  - title: Interface de ligne de commande
    icon: "./media/cli_line.png"
    url: https://docs.netapp.com/us-en/e-series-cli/index.html
    summary: Utilisez l'interface de ligne de commandes pour configurer et contrôler
      vos systèmes de stockage E-Series à partir d'une invite de systèmes d'exploitation.
    tags: all, tag_storage_management, tag_SANtricity
  - title: API de services Web
    icon: "./media/api.png"
    url: https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html
    summary: Utilisez l'API RESTful pour créer et automatiser des workflows sur vos
      systèmes de stockage E-Series nouveaux et existants.
    tags: all, tag_storage_management, tag_SANtricity
  - title: BeeGFS sur NetApp avec E-Series Storage
    icon: "./media/api.png"
    url: https://docs.netapp.com/us-en/beegfs/index.html
    summary: Utilisez BeeGFS sur NetApp pour créer et déployer une infrastructure
      haute disponibilité qui combine le système de fichiers parallèle BeeGFS avec
      les systèmes de stockage NetApp EF600.
    tags: all, tag_solution
